import matplotlib.pyplot as plt
import cv2
from PIL import Image

# image1 = Image.open('predictions/cat2_resnet.jpg')
# image2 = Image.open('predictions/cat3_resnet.jpg')
# image3 = Image.open('predictions/cat4_resnet.jpg')
# image4 = Image.open('predictions/cat5_resnet.jpg')
# image5 = Image.open('predictions/dog2_resnet.jpg')
# image6 = Image.open('predictions/dog3_resnet.jpg')
# image7 = Image.open('predictions/dog4_resnet.jpg')
# image8 = Image.open('predictions/dog5_resnet.jpg')

# image1 = Image.open('predictions/cat2_vgg.jpg')
# image2 = Image.open('predictions/cat3_vgg.jpg')
# image3 = Image.open('predictions/cat4_vgg.jpg')
# image4 = Image.open('predictions/cat5_vgg.jpg')
# image5 = Image.open('predictions/dog2_vgg.jpg')
# image6 = Image.open('predictions/dog3_vgg.jpg')
# image7 = Image.open('predictions/dog4_vgg.jpg')
# image8 = Image.open('predictions/dog5_vgg.jpg')

# image1 = Image.open('predictions/catAndDog2Resnet.jpg')
# image5 = Image.open('predictions/catAndDog2VGG.jpg')
# image2 = Image.open('predictions/catAndDogResnet.jpg')
# image6 = Image.open('predictions/catAndDogVGG.jpg')
# image3 = Image.open('predictions/catsAndDogs2Resnet.jpg')
# image7 = Image.open('predictions/catsAndDogs2VGG.jpg')
# image4 = Image.open('predictions/catsAndDogsResnet.jpg')
# image8 = Image.open('predictions/catsAndDogsVGG.jpg')

# image1 = Image.open('predictions/cat2_custom.jpg')
# image2 = Image.open('predictions/cat3_custom.jpg')
# image3 = Image.open('predictions/cat4_custom.jpg')
# image4 = Image.open('predictions/cat5_custom.jpg')
# image5 = Image.open('predictions/dog2_custom.jpg')
# image6 = Image.open('predictions/dog3_custom.jpg')
# image7 = Image.open('predictions/dog4_custom.jpg')
# image8 = Image.open('predictions/dog5_custom.jpg')

image1 = Image.open('predictions/catAndDog2Resnet.jpg')
image5 = Image.open('predictions/catAndDog2Custom.jpg')
image2 = Image.open('predictions/catAndDogResnet.jpg')
image6 = Image.open('predictions/catAndDogCustom.jpg')
image3 = Image.open('predictions/catsAndDogs2Resnet.jpg')
image7 = Image.open('predictions/catsAndDogs2Custom.jpg')
image4 = Image.open('predictions/catsAndDogsResnet.jpg')
image8 = Image.open('predictions/catsAndDogsCustom.jpg')

fig, axs = plt.subplots(2, 4)  # Create a grid of 2 rows and 3 columns
axs[0, 0].imshow(image1)
axs[0, 0].axis('off')  # Turn off axis labels
axs[0, 1].imshow(image2)
axs[0, 1].axis('off')
axs[0, 2].imshow(image3)
axs[0, 2].axis('off')
axs[0, 3].imshow(image4)
axs[0, 3].axis('off')
axs[1, 0].imshow(image5)
axs[1, 0].axis('off')
axs[1, 1].imshow(image6)
axs[1, 1].axis('off')
axs[1, 2].imshow(image7)
axs[1, 2].axis('off')
axs[1, 3].imshow(image8)
axs[1, 3].axis('off')
plt.show()